[colors.bright]
black = "#2640D3"
blue = "#EB3131"
cyan = "#2AAAB8"        # Color6Intense
green = "#1C948C"       # Color2Intense
magenta = "#AA32E1"     # Color5Intense
red = "#E73259"         # Color1Intense
white = "#FFFFFF"       # Color7Intense
yellow = "#A9C413"      # Color3Intense

[colors.normal]
black = "#2640D3"
blue = "#EB3131"
cyan = "#2AAAB8"        # Color6Intense
green = "#1C948C"       # Color2Intense
magenta = "#AA32E1"     # Color5Intense
red = "#E73259"         # Color1Intense
white = "#FFFFFF"       # Color7Intense
yellow = "#A9C413"      # Color3Intense

[colors.primary]
background = "#1B1B1D"  # Background
foreground = "#FFFFFF"  # Foreground

[font]
size = 10.5

[font.normal]
family = "CaskaydiaCoveNerdFontMono"
style = "Regular"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "COntrol"


[terminal.shell]
program = "/bin/fish"

[window]
opacity = 1

[window.dimensions]
columns = 100
lines = 25

[window.padding]
x = 18
y = 13


